apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: print-hello-world
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-hello-world
            image: robinlinacre/test_rpy
          restartPolicy: OnFailure
